package dev.applewatchandroid.bridge;

import org.bouncycastle.crypto.digests.SHA256Digest;
import org.bouncycastle.crypto.digests.SHA512Digest;
import org.bouncycastle.crypto.generators.HKDFBytesGenerator;
import org.bouncycastle.crypto.generators.PKCS5S2ParametersGenerator;
import org.bouncycastle.crypto.macs.HMac;
import org.bouncycastle.crypto.params.HKDFParameters;
import org.bouncycastle.crypto.params.KeyParameter;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;

/**
 * Secret derivation recovered from the Apple Watch salted-PIN pairing profile.
 *
 * <p>No method in this class formats a PIN or key for logging. The supplied
 * PIN character array is consumed and zeroed even when validation fails.</p>
 */
final class AppleWatchPairingCrypto {
    static final int PIN_LENGTH = 6;
    static final int PIN_SALT_MINIMUM_LENGTH = 32;
    static final int WATCH_SETUP_DATA_LENGTH = 12;
    static final int PIN_KEY_LENGTH = 32;
    static final int PPK_LENGTH = 64;
    static final int PBKDF2_ITERATIONS = 1_600_000;
    static final int PPK_ID_TYPE_FIXED = 1;
    static final String SALTED_PIN_KEY_ID =
            "com.apple.networkrelay.companionlink.pairing.auth.saltedPin";

    private static final byte[] PPK_INFO =
            "Derived IKEv2 PPK for terminus device pairing"
                    .getBytes(StandardCharsets.US_ASCII);
    private static final byte[] SALTED_PIN_KEY_ID_BYTES =
            SALTED_PIN_KEY_ID.getBytes(StandardCharsets.UTF_8);

    private AppleWatchPairingCrypto() {
    }

    /**
     * Consumes a six-digit Watch PIN and derives both the SPAKE2+ seed and the
     * mandatory IKEv2 PPK. The caller-owned {@code pin} is always zeroed.
     */
    static PairingSecrets derive(
            char[] pin,
            byte[] pinSalt,
            byte[] watchSetupData) {
        byte[] authenticationData = null;
        byte[] pinKey = null;
        byte[] sharedSecret = null;
        byte[] ppk = null;
        try {
            int numericPin = parseAndConsumePin(pin);
            requireMinimumLength(
                    "Watch PIN salt",
                    pinSalt,
                    PIN_SALT_MINIMUM_LENGTH);
            requireLength(
                    "Watch setup data",
                    watchSetupData,
                    WATCH_SETUP_DATA_LENGTH);

            authenticationData = new byte[]{
                    (byte) (numericPin >>> 24),
                    (byte) (numericPin >>> 16),
                    (byte) (numericPin >>> 8),
                    (byte) numericPin
            };
            pinKey = pbkdf2Sha256(
                    authenticationData,
                    pinSalt,
                    PBKDF2_ITERATIONS,
                    PIN_KEY_LENGTH);
            sharedSecret = new byte[
                    PIN_KEY_LENGTH + WATCH_SETUP_DATA_LENGTH];
            System.arraycopy(
                    pinKey,
                    0,
                    sharedSecret,
                    0,
                    PIN_KEY_LENGTH);
            System.arraycopy(
                    watchSetupData,
                    0,
                    sharedSecret,
                    PIN_KEY_LENGTH,
                    WATCH_SETUP_DATA_LENGTH);
            ppk = hkdfSha512(
                    sharedSecret,
                    pinSalt,
                    PPK_INFO,
                    PPK_LENGTH);
            return new PairingSecrets(
                    authenticationData,
                    pinKey,
                    sharedSecret,
                    ppk);
        } finally {
            wipe(authenticationData);
            wipe(pinKey);
            wipe(sharedSecret);
            wipe(ppk);
            if (pin != null) {
                Arrays.fill(pin, '\0');
            }
        }
    }

    /**
     * Implements Apple's
     * {@code -deriveKeyFromPrimeKey:hmacContext:}: the first RFC 8784
     * {@code prf+} block, {@code PRF(PPK, oldKey | 0x01)}.
     */
    static byte[] deriveKeyFromPrimeKey(
            byte[] ppk,
            byte[] primeKey) {
        requireLength("IKE PPK", ppk, PPK_LENGTH);
        if (primeKey == null || primeKey.length == 0) {
            throw new IllegalArgumentException(
                    "IKE prime key is required");
        }
        byte[] input = Arrays.copyOf(
                primeKey,
                primeKey.length + 1);
        input[input.length - 1] = 0x01;
        try {
            return hmacSha512(ppk, input);
        } finally {
            wipe(input);
        }
    }

    /**
     * The fixed PPK identity generated by NetworkExtension for this profile.
     * Type 1 is present and its opaque value is empty.
     */
    static byte[] fixedPpkIdentityData() {
        return new byte[]{PPK_ID_TYPE_FIXED};
    }

    /**
     * Serialized IKE IDi payload body used by a physical Apple pairing
     * initiator. The pairing-candidate UUID KEY_ID belongs only to Apple's
     * Simulator/Hypervisor branch.
     */
    static byte[] physicalInitiatorIdPayloadBody() {
        return new byte[]{
                (byte) IkeV2SessionCrypto.ID_TYPE_NULL,
                0,
                0,
                0
        };
    }

    /**
     * Serialized IKE IDr payload body for the Watch salted-PIN profile.
     */
    static byte[] saltedPinIdPayloadBody() {
        return keyIdPayloadBody(SALTED_PIN_KEY_ID_BYTES);
    }

    private static byte[] keyIdPayloadBody(
            byte[] identifier) {
        byte[] body = new byte[4 + identifier.length];
        body[0] = (byte) IkeV2SessionCrypto.ID_TYPE_KEY_ID;
        System.arraycopy(
                identifier,
                0,
                body,
                4,
                identifier.length);
        return body;
    }

    private static int parseAndConsumePin(char[] pin) {
        if (pin == null || pin.length != PIN_LENGTH) {
            throw new IllegalArgumentException(
                    "Watch PIN must contain exactly six digits");
        }
        int value = 0;
        for (char digit : pin) {
            if (digit < '0' || digit > '9') {
                throw new IllegalArgumentException(
                        "Watch PIN must contain exactly six digits");
            }
            value = value * 10 + digit - '0';
        }
        return value;
    }

    private static byte[] pbkdf2Sha256(
            byte[] password,
            byte[] salt,
            int iterations,
            int length) {
        PKCS5S2ParametersGenerator generator =
                new PKCS5S2ParametersGenerator(new SHA256Digest());
        generator.init(password, salt, iterations);
        byte[] generated = ((KeyParameter) generator
                .generateDerivedParameters(length * 8))
                .getKey();
        return Arrays.copyOf(generated, length);
    }

    private static byte[] hkdfSha512(
            byte[] inputKeyMaterial,
            byte[] salt,
            byte[] info,
            int length) {
        HKDFBytesGenerator generator =
                new HKDFBytesGenerator(new SHA512Digest());
        generator.init(new HKDFParameters(
                inputKeyMaterial,
                salt,
                info));
        byte[] output = new byte[length];
        generator.generateBytes(output, 0, output.length);
        return output;
    }

    private static byte[] hmacSha512(
            byte[] key,
            byte[] data) {
        HMac hmac = new HMac(new SHA512Digest());
        hmac.init(new KeyParameter(key));
        hmac.update(data, 0, data.length);
        byte[] output = new byte[hmac.getMacSize()];
        hmac.doFinal(output, 0);
        return output;
    }

    private static void requireLength(
            String label,
            byte[] value,
            int expectedLength) {
        if (value == null || value.length != expectedLength) {
            throw new IllegalArgumentException(
                    label + " must be " + expectedLength + " bytes");
        }
    }

    private static void requireMinimumLength(
            String label,
            byte[] value,
            int minimumLength) {
        if (value == null || value.length < minimumLength) {
            throw new IllegalArgumentException(
                    label + " must be at least "
                            + minimumLength
                            + " bytes");
        }
    }

    private static void wipe(byte[] bytes) {
        if (bytes != null) {
            Arrays.fill(bytes, (byte) 0);
        }
    }

    static final class PairingSecrets {
        final byte[] authenticationData;
        final byte[] pinKey;
        final byte[] sharedSecret;
        final byte[] ppk;
        private boolean destroyed;

        PairingSecrets(
                byte[] authenticationData,
                byte[] pinKey,
                byte[] sharedSecret,
                byte[] ppk) {
            this.authenticationData =
                    authenticationData.clone();
            this.pinKey = pinKey.clone();
            this.sharedSecret = sharedSecret.clone();
            this.ppk = ppk.clone();
        }

        void destroy() {
            wipe(authenticationData);
            wipe(pinKey);
            wipe(sharedSecret);
            wipe(ppk);
            destroyed = true;
        }

        boolean isDestroyed() {
            return destroyed;
        }
    }
}
