package dev.applewatchandroid.bridge;

import java.util.Objects;

/**
 * The three-part IDS name transported as the Network.framework
 * service-connector service string.
 *
 * <p>IDSGenericConnectionID emits {@code account/service/name}. The ordinary
 * local-delivery path uses account {@code idstest}, service
 * {@code localdelivery}, and an IDSUTunConnection runtime identifier as the
 * third component. NanoRegistry topic names are not service-connector names;
 * they are multiplexed later inside the accepted IDS data stream.</p>
 */
final class IdsServiceConnectorName {
    static final String LOCAL_ACCOUNT =
            "idstest";
    static final String LOCAL_DELIVERY_SERVICE =
            "localdelivery";

    final String account;
    final String service;
    final String name;

    private IdsServiceConnectorName(
            String account,
            String service,
            String name) {
        this.account =
                requireCanonicalComponent(
                        account,
                        "account");
        this.service =
                requireCanonicalComponent(
                        service,
                        "service");
        this.name =
                requireCanonicalComponent(
                        name,
                        "name");
    }

    static IdsServiceConnectorName of(
            String account,
            String service,
            String name) {
        return new IdsServiceConnectorName(
                account,
                service,
                name);
    }

    static IdsServiceConnectorName localDelivery(
            String runtimeConnectionName) {
        return of(
                LOCAL_ACCOUNT,
                LOCAL_DELIVERY_SERVICE,
                runtimeConnectionName);
    }

    /**
     * Parses the canonical outbound representation generated by IDS.
     */
    static IdsServiceConnectorName parseCanonical(
            String encoded) {
        String[] components =
                split(
                        encoded);
        if (components.length != 3) {
            throw new IllegalArgumentException(
                    "Canonical IDS service-connector name needs 3 components");
        }
        return of(
                components[0],
                components[1],
                components[2]);
    }

    static IdsServiceConnectorName parseLenient(
            String encoded) {
        if (encoded == null) {
            throw new IllegalArgumentException(
                    "Encoded IDS service-connector name is absent");
        }
        if ("nano-class-d".equals(encoded)
                || encoded.contains("class-d")
                || (encoded.endsWith("-D") && !encoded.contains("/"))) {
            return localDelivery(
                    IdsUtunConnectionName.defaultPaired(
                            IdsUtunConnectionName.PRIORITY_URGENT,
                            IdsUtunConnectionName.PROTECTION_CLASS_D));
        }
        if ("nano-class-c".equals(encoded)
                || encoded.contains("class-c")
                || (encoded.endsWith("-C") && !encoded.contains("/"))) {
            return localDelivery(
                    IdsUtunConnectionName.defaultPaired(
                            IdsUtunConnectionName.PRIORITY_URGENT,
                            IdsUtunConnectionName.PROTECTION_CLASS_C));
        }
        return parseAppleCompatiblePrefix(
                encoded);
    }

    /**
     * Mirrors the watch-side IDSUTunController receiver in watchOS 26.2.
     *
     * <p>The Apple receiver rejects fewer than three slash-separated
     * components, then consumes indexes 0, 1, and 2. It does not reject
     * trailing components at that point. Outbound code should always use the
     * canonical three-component representation.</p>
     */
    static IdsServiceConnectorName parseAppleCompatiblePrefix(
            String encoded) {
        String[] components =
                split(
                        encoded);
        if (components.length < 3) {
            throw new IllegalArgumentException(
                    "IDS service-connector name needs at least 3 components");
        }
        return of(
                components[0],
                components[1],
                components[2]);
    }

    boolean isLocalDelivery() {
        return LOCAL_ACCOUNT.equals(
                account)
                && LOCAL_DELIVERY_SERVICE.equals(
                service);
    }

    String encode() {
        return account
                + "/"
                + service
                + "/"
                + name;
    }

    @Override
    public String toString() {
        return encode();
    }

    @Override
    public boolean equals(
            Object other) {
        if (this == other) {
            return true;
        }
        if (!(other
                instanceof IdsServiceConnectorName that)) {
            return false;
        }
        return account.equals(
                that.account)
                && service.equals(
                that.service)
                && name.equals(
                that.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                account,
                service,
                name);
    }

    private static String[] split(
            String encoded) {
        if (encoded == null
                || encoded.isEmpty()
                || encoded.indexOf(
                        '\0') >= 0) {
            throw new IllegalArgumentException(
                    "IDS service-connector name is absent or contains NUL");
        }
        return encoded.split(
                "/",
                -1);
    }

    private static String requireCanonicalComponent(
            String component,
            String label) {
        if (component == null
                || component.isEmpty()
                || component.indexOf(
                        '/') >= 0
                || component.indexOf(
                        '\0') >= 0) {
            throw new IllegalArgumentException(
                    "IDS service-connector "
                            + label
                            + " is invalid");
        }
        return component;
    }
}
