cmake_minimum_required(VERSION 3.22.1)
project(optical_reader LANGUAGES CXX)
if(ANDROID_ABI STREQUAL "arm64-v8a")
    add_library(optical_reader SHARED optical_reader.cpp)
else()
    add_library(optical_reader SHARED optical_unsupported.cpp)
endif()
target_compile_features(optical_reader PRIVATE cxx_std_17)
target_compile_options(optical_reader PRIVATE -Wall -Wextra -fvisibility=hidden)
target_link_options(optical_reader PRIVATE "-Wl,-z,max-page-size=16384")
