package dev.applewatchandroid.bridge;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import org.junit.Test;

/**
 * Verifies activation-body canonicalization against synthetic material:
 * the XML container must re-serialize
 * byte-identically to the python plistlib canonical binary plist reference
 * (FMT_BINARY, sort_keys=True). Certificates, keys and device identifiers are
 * deliberately invalid test data generated by build_synthetic_activation_fixtures.py.
 */
public final class ActivationResponseCanonicalizerTest {
    @Test
    public void defaultAndInvalidOverridePreserveSignedBytes() throws Exception {
        java.nio.file.Path directory = java.nio.file.Files.createTempDirectory("activation-delivery-");
        String previous = System.getProperty("watch.files");
        byte[] wire = resource("/activation/activation-resolved-body-2202.bin");
        try {
            System.setProperty("watch.files", directory.toString());
            var result = ActivationResponseCanonicalizer.maybeTransform(wire);
            assertEquals("raw", result.variant());
            assertFalse(result.changed());
            assertArrayEquals(wire, result.body());
            java.nio.file.Files.writeString(directory.resolve("activation-delivery-variant.txt"), "invalid");
            assertArrayEquals(wire, ActivationResponseCanonicalizer.maybeTransform(wire).body());
            java.nio.file.Files.writeString(directory.resolve("activation-delivery-variant.txt"), "bplist");
            assertTrue(ActivationResponseCanonicalizer.maybeTransform(wire).changed());
        } finally {
            if (previous == null) System.clearProperty("watch.files"); else System.setProperty("watch.files", previous);
            java.nio.file.Files.deleteIfExists(directory.resolve("activation-delivery-variant.txt"));
            java.nio.file.Files.delete(directory);
        }
    }
    @Test
    public void bplistMatchesPythonCanonicalReference() throws Exception {
        byte[] wire = resource("/activation/activation-resolved-body-2202.bin");
        byte[] reference =
                resource("/activation/activation-record-2202-canonical.bplist");
        assertTrue(wire.length > reference.length);
        ActivationResponseCanonicalizer.Result result =
                ActivationResponseCanonicalizer.maybeTransform(wire, "bplist");
        assertTrue(result.changed());
        assertEquals("bplist", result.variant());
        assertEquals(wire.length, result.inputLength());
        assertArrayEquals(reference, result.body());
    }

    @Test
    public void xmlVariantRoundTripsToSameCanonicalBinary() throws Exception {
        byte[] wire = resource("/activation/activation-resolved-body-2202.bin");
        byte[] reference =
                resource("/activation/activation-record-2202-canonical.bplist");
        ActivationResponseCanonicalizer.Result xmlResult =
                ActivationResponseCanonicalizer.maybeTransform(wire, "xml");
        assertTrue(xmlResult.changed());
        String xml = new String(xmlResult.body(), StandardCharsets.UTF_8);
        assertTrue(xml.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\""
                + " \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
                + "<plist version=\"1.0\">\n<dict>\n"));
        assertTrue(xml.endsWith("</dict>\n</plist>\n"));
        assertTrue(xml.contains("\t<key>ActivationRecord</key>\n"));
        assertTrue(xml.contains("\t\t<key>unbrick</key>\n\t\t<true/>\n"));
        // Re-encoding the Apple-style XML must land on the same canonical
        // binary form, proving parser and writer are consistent.
        ActivationResponseCanonicalizer.Result reparsed =
                ActivationResponseCanonicalizer.maybeTransform(
                        xmlResult.body(), "bplist");
        assertTrue(reparsed.changed());
        assertArrayEquals(reference, reparsed.body());
    }

    @Test
    public void recordBplistMatchesPythonCanonicalReference() throws Exception {
        byte[] wire = resource("/activation/activation-resolved-body-2202.bin");
        byte[] reference =
                resource("/activation/activation-record-inner-2202.bplist");
        assertTrue(reference.length > 4096);
        ActivationResponseCanonicalizer.Result result =
                ActivationResponseCanonicalizer.maybeTransform(
                        wire, "record-bplist");
        assertTrue(result.changed());
        assertEquals("record-bplist", result.variant());
        assertArrayEquals(reference, result.body());
        // The bare record carries the activation material on top level.
        Object decoded = AppleBinaryPropertyList.decode(result.body());
        assertTrue(decoded instanceof java.util.Map<?, ?>);
        java.util.Map<?, ?> record = (java.util.Map<?, ?>) decoded;
        assertTrue(record.containsKey("AccountToken"));
        assertTrue(record.containsKey("AccountTokenSignature"));
        assertTrue(record.containsKey("DeviceCertificate"));
        assertFalse(record.containsKey("ActivationRecord"));
    }

    @Test
    public void recordNoudcBplistStripsUniqueDeviceCertificate() throws Exception {
        byte[] wire = resource("/activation/activation-resolved-body-2202.bin");
        ActivationResponseCanonicalizer.Result result =
                ActivationResponseCanonicalizer.maybeTransform(
                        wire, "record-noudc-bplist");
        assertTrue(result.changed());
        Object decoded = AppleBinaryPropertyList.decode(result.body());
        assertTrue(decoded instanceof java.util.Map<?, ?>);
        java.util.Map<?, ?> record = (java.util.Map<?, ?>) decoded;
        assertFalse(record.containsKey("UniqueDeviceCertificate"));
        assertTrue(record.containsKey("AccountToken"));
        assertTrue(record.containsKey("AccountTokenSignature"));
        assertTrue(record.containsKey("DeviceCertificate"));
        assertTrue(record.containsKey("unbrick"));
        assertEquals(7, record.size());
    }

    @Test
    public void rawVariantPassesBytesThrough() throws Exception {
        byte[] wire = resource("/activation/activation-resolved-body-2202.bin");
        ActivationResponseCanonicalizer.Result result =
                ActivationResponseCanonicalizer.maybeTransform(wire, "raw");
        assertFalse(result.changed());
        assertArrayEquals(wire, result.body());
    }

    @Test
    public void buddymlRetryPagePassesThrough() throws Exception {
        byte[] buddyml = resource("/activation/activation-buddyml-retry-2132.bin");
        ActivationResponseCanonicalizer.Result result =
                ActivationResponseCanonicalizer.maybeTransform(buddyml, "bplist");
        assertFalse(result.changed());
        assertArrayEquals(buddyml, result.body());
    }

    @Test
    public void garbageAndEmptyPassThrough() {
        assertFalse(ActivationResponseCanonicalizer.maybeTransform(
                null, "bplist").changed());
        assertFalse(ActivationResponseCanonicalizer.maybeTransform(
                new byte[0], "bplist").changed());
        assertFalse(ActivationResponseCanonicalizer.maybeTransform(
                "bplist00-fake".getBytes(StandardCharsets.US_ASCII),
                "bplist").changed());
        assertFalse(ActivationResponseCanonicalizer.maybeTransform(
                "<plist><dict><key>Other</key><true/></dict></plist>"
                        .getBytes(StandardCharsets.UTF_8),
                "bplist").changed());
    }

    private static byte[] resource(String name) throws Exception {
        try (InputStream input =
                ActivationResponseCanonicalizerTest.class.getResourceAsStream(name)) {
            assertNotNull("missing test resource " + name, input);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            input.transferTo(out);
            return out.toByteArray();
        }
    }
}
