package dev.applewatchandroid.bridge;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;

import java.io.ByteArrayOutputStream;
import java.util.Arrays;
import java.util.List;

import org.junit.Test;

public final class IdsSocketPairCodecTest {
    private static final String MESSAGE_UUID =
            "00112233-4455-6677-8899-aabbccddeeff";

    @Test
    public void nanoRequestsMatchIndependentAppleIdsFoundationFixtures() throws Exception {
        // Generated by Apple's macOS IDSFoundation, then independently parsed there.
        // These are synthetic fixtures, not captures containing Watch identifiers.
        for (int type = 4; type <= 5; type++) {
            byte[] nativeFrame;
            try (var source = getClass().getResourceAsStream(
                    "/ids/socketpair-protobuf-" + type + "-native.bin")) {
                assertNotNull(source);
                nativeFrame = source.readAllBytes();
            }
            String topic = "com.apple.private.alloy.bluetoothregistry"
                    + (type == 4 ? "classc" : "");
            byte[] payload = type == 4 ? new byte[0]
                    : hex("08 ac 02 11 00 00 00 00 00 00 20 40 18 00");
            var outgoing = new IdsSocketPairCodec.ProtobufMessage(
                    0x11223344L, 7, 0x15, null, MESSAGE_UUID, topic,
                    type, false, payload, null);
            var decoded = (IdsSocketPairCodec.ProtobufMessage)
                    IdsSocketPairCodec.decode(nativeFrame);
            try {
                assertArrayEquals(nativeFrame, IdsSocketPairCodec.encodeProtobuf(outgoing));
                assertEquals(3, decoded.command);
                assertEquals(type, decoded.protobufType);
                assertFalse(decoded.response);
                assertEquals(0x11223344L, decoded.sequence);
                assertEquals(7, decoded.streamId);
                assertEquals(0x15, decoded.flags);
                assertEquals(MESSAGE_UUID, decoded.messageUuid);
                assertEquals(topic, decoded.topic);
                assertNull(decoded.peerResponseIdentifier);
                assertArrayEquals(payload, decoded.payload);
            } finally {
                outgoing.destroy();
                decoded.destroy();
            }
        }
    }

    @Test
    public void dictionaryMatchesIndependentAppleIdsFoundationFixture() throws Exception {
        byte[] nativeFrame;
        try (var source = getClass().getResourceAsStream("/ids/socketpair-dictionary-native.bin")) {
            assertNotNull(source);
            nativeFrame = source.readAllBytes();
        }
        try (var decoder = new IdsSocketPairCodec.StreamDecoder()) {
            assertTrue(decoder.push(Arrays.copyOfRange(nativeFrame, 0, 11)).isEmpty());
            var messages = decoder.push(Arrays.copyOfRange(nativeFrame, 11, nativeFrame.length));
            try {
                assertEquals(1, messages.size());
                assertTrue(messages.get(0) instanceof IdsSocketPairCodec.DataMessage);
                var dictionary = (IdsSocketPairCodec.DataMessage) messages.get(0);
                assertEquals(6, dictionary.command);
                assertEquals(0x11223344L, dictionary.sequence);
                assertEquals(7, dictionary.streamId);
                assertEquals(0x15, dictionary.flags);
                assertEquals(MESSAGE_UUID, dictionary.messageUuid);
                assertEquals(IdsDeviceInfoExchange.TOPIC, dictionary.topic);
                var payload = (java.util.Map<?, ?>) AppleBinaryPropertyList.decode(dictionary.payload);
                assertEquals(17L, payload.get("command"));
                assertEquals(List.of("com.apple.madrid"), payload.get("serviceTypes"));
                assertArrayEquals(nativeFrame, IdsSocketPairCodec.encodeData(dictionary));
            } finally { messages.forEach(IdsSocketPairCodec.Message::destroy); }
        }
        // It is no longer an opaque unknown command: a truncated common header is invalid.
        assertThrows(IllegalArgumentException.class, () -> IdsSocketPairCodec.decode(hex("06 00000003 fffefd")));
    }

    @Test
    public void unsupportedCommandDoesNotDesynchronizeTheFollowingKnownFrame() {
        byte[] unknown = hex("7f 00000003 fffefd");
        byte[] ack = IdsSocketPairCodec.encodeAck(0x11223344L, false);
        byte[] combined = new byte[unknown.length + ack.length];
        System.arraycopy(unknown, 0, combined, 0, unknown.length);
        System.arraycopy(ack, 0, combined, unknown.length, ack.length);
        try (var decoder = new IdsSocketPairCodec.StreamDecoder()) {
            assertTrue(decoder.push(Arrays.copyOfRange(combined, 0, 4)).isEmpty());
            var messages = decoder.push(Arrays.copyOfRange(combined, 4, combined.length));
            try {
                assertEquals(2, messages.size());
                assertTrue(messages.get(0) instanceof IdsSocketPairCodec.UnknownMessage);
                assertEquals(0x7f, messages.get(0).command);
                assertEquals(0x11223344L, ((IdsSocketPairCodec.AckMessage) messages.get(1)).sequence);
            } finally { messages.forEach(IdsSocketPairCodec.Message::destroy); }
        }
    }

    @Test
    public void serviceMapSkipsFirmwareExtensionFieldsWithoutLosingFraming() {
        // Known fields around an unknown extension, as IDSFoundation ReadField does.
        byte[] frame = hex("27 00000016 01 0001 01 7f 0002 cafe 02 0002 0007 03 0005 68656c6c6f");
        IdsSocketPairCodec.ServiceMapMessage parsed =
                (IdsSocketPairCodec.ServiceMapMessage) IdsSocketPairCodec.decode(frame);
        try {
            assertEquals(7, parsed.streamId);
            assertEquals("hello", parsed.serviceName);
        } finally {
            parsed.destroy();
        }
        byte[] truncated = hex("27 00000004 7f 0002 ca");
        assertThrows(IllegalArgumentException.class, () -> IdsSocketPairCodec.decode(truncated));
    }

    @Test
    public void encodesCurrentHandshakeAckAndEmptyKeepAliveExactly() {
        assertArrayEquals(
                hex("04 00 00 00 04 00 00 00 01"),
                IdsSocketPairCodec.encodeHandshake(1));
        assertArrayEquals(
                hex("01 00 00 00 04 11 22 33 44"),
                IdsSocketPairCodec.encodeAck(
                        0x11223344L,
                        false));
        assertArrayEquals(
                hex("25 00 00 00 04 11 22 33 44"),
                IdsSocketPairCodec.encodeAck(
                        0x11223344L,
                        true));
        assertArrayEquals(
                hex("02 00 00 00 00"),
                IdsSocketPairCodec.encodeKeepAlive());

        IdsSocketPairCodec.HandshakeMessage handshake =
                (IdsSocketPairCodec.HandshakeMessage)
                        IdsSocketPairCodec.decode(
                                IdsSocketPairCodec.encodeHandshake(
                                        1));
        IdsSocketPairCodec.AckMessage ack =
                (IdsSocketPairCodec.AckMessage)
                        IdsSocketPairCodec.decode(
                                IdsSocketPairCodec.encodeAck(
                                        0x11223344L,
                                        false));
        IdsSocketPairCodec.KeepAliveMessage keepAlive =
                (IdsSocketPairCodec.KeepAliveMessage)
                        IdsSocketPairCodec.decode(
                                IdsSocketPairCodec.encodeKeepAlive());
        try {
            assertEquals(1, handshake.version);
            assertEquals(0x11223344L, ack.sequence);
            assertEquals(
                    IdsSocketPairCodec.COMMAND_KEEP_ALIVE,
                    keepAlive.command);
        } finally {
            handshake.destroy();
            ack.destroy();
            keepAlive.destroy();
        }
    }

    @Test
    public void dataMatchesExactAllFlagsWireVector() {
        byte[] payload =
                hex("de ad");
        IdsSocketPairCodec.DataMessage source =
                new IdsSocketPairCodec.DataMessage(
                        0x01020304L,
                        0x1234,
                        0x3f,
                        "r",
                        MESSAGE_UUID,
                        "svc",
                        payload,
                        0x11223344L);
        byte[] encoded =
                IdsSocketPairCodec.encodeData(
                        source);
        IdsSocketPairCodec.DataMessage decoded =
                (IdsSocketPairCodec.DataMessage)
                        IdsSocketPairCodec.decode(
                                encoded);
        try {
            assertArrayEquals(
                    hex(
                            "00 00 00 00 41 "
                                    + "01 02 03 04 12 34 3f "
                                    + "00 00 00 01 72 "
                                    + "00 00 00 24 "
                                    + "30 30 31 31 32 32 33 33 "
                                    + "2d 34 34 35 35 "
                                    + "2d 36 36 37 37 "
                                    + "2d 38 38 39 39 "
                                    + "2d 61 61 62 62 63 63 64 64 "
                                    + "65 65 66 66 "
                                    + "00 00 00 03 73 76 63 "
                                    + "de ad 11 22 33 44"),
                    encoded);
            assertEquals(0x01020304L, decoded.sequence);
            assertEquals(0x1234, decoded.streamId);
            assertEquals(0x3f, decoded.flags);
            assertEquals("r", decoded.peerResponseIdentifier);
            assertEquals(MESSAGE_UUID, decoded.messageUuid);
            assertEquals("svc", decoded.topic);
            assertArrayEquals(payload, decoded.payload);
            assertEquals(
                    Long.valueOf(
                            0x11223344L),
                    decoded.expirySeconds);
        } finally {
            source.destroy();
            decoded.destroy();
            wipe(payload);
            wipe(encoded);
        }
    }

    @Test
    public void protobufUsesTypeResponseLengthPayloadOrder() {
        byte[] payload =
                hex("aa bb cc");
        IdsSocketPairCodec.ProtobufMessage source =
                new IdsSocketPairCodec.ProtobufMessage(
                        0x01020304L,
                        0x1234,
                        0,
                        null,
                        MESSAGE_UUID,
                        null,
                        0x4567,
                        true,
                        payload,
                        null);
        byte[] encoded =
                IdsSocketPairCodec.encodeProtobuf(
                        source);
        IdsSocketPairCodec.ProtobufMessage decoded =
                (IdsSocketPairCodec.ProtobufMessage)
                        IdsSocketPairCodec.decode(
                                encoded);
        try {
            assertArrayEquals(
                    hex(
                            "03 00 00 00 3e "
                                    + "01 02 03 04 12 34 00 "
                                    + "00 00 00 00 "
                                    + "00 00 00 24 "
                                    + "30 30 31 31 32 32 33 33 "
                                    + "2d 34 34 35 35 "
                                    + "2d 36 36 37 37 "
                                    + "2d 38 38 39 39 "
                                    + "2d 61 61 62 62 63 63 64 64 "
                                    + "65 65 66 66 "
                                    + "45 67 00 01 "
                                    + "00 00 00 03 aa bb cc"),
                    encoded);
            assertEquals(0x4567, decoded.protobufType);
            assertTrue(decoded.response);
            assertArrayEquals(payload, decoded.payload);
            assertNull(decoded.topic);
            assertNull(decoded.expirySeconds);
        } finally {
            source.destroy();
            decoded.destroy();
            wipe(payload);
            wipe(encoded);
        }
    }

    @Test
    public void appAckAndServiceMapMatchExactWireVectors() {
        IdsSocketPairCodec.AppAckMessage appAck =
                new IdsSocketPairCodec.AppAckMessage(
                        0x01020304L,
                        0x1234,
                        "id",
                        "svc");
        IdsSocketPairCodec.ServiceMapMessage serviceMap =
                new IdsSocketPairCodec.ServiceMapMessage(
                        1,
                        0x1234,
                        "abc");
        byte[] encodedAck =
                IdsSocketPairCodec.encodeAppAck(
                        appAck);
        byte[] encodedMap =
                IdsSocketPairCodec.encodeServiceMap(
                        serviceMap);
        try {
            assertArrayEquals(
                    hex(
                            "07 00 00 00 13 "
                                    + "01 02 03 04 12 34 "
                                    + "00 00 00 02 69 64 "
                                    + "00 00 00 03 73 76 63"),
                    encodedAck);
            assertArrayEquals(
                    hex(
                            "27 00 00 00 0f "
                                    + "01 00 01 01 "
                                    + "02 00 02 12 34 "
                                    + "03 00 03 61 62 63"),
                    encodedMap);

            IdsSocketPairCodec.AppAckMessage decodedAck =
                    (IdsSocketPairCodec.AppAckMessage)
                            IdsSocketPairCodec.decode(
                                    encodedAck);
            IdsSocketPairCodec.ServiceMapMessage decodedMap =
                    (IdsSocketPairCodec.ServiceMapMessage)
                            IdsSocketPairCodec.decode(
                                    encodedMap);
            try {
                assertEquals("id", decodedAck.peerResponseIdentifier);
                assertEquals("svc", decodedAck.topic);
                assertEquals(1, decodedMap.reason);
                assertEquals(0x1234, decodedMap.streamId);
                assertEquals("abc", decodedMap.serviceName);
            } finally {
                decodedAck.destroy();
                decodedMap.destroy();
            }
        } finally {
            appAck.destroy();
            serviceMap.destroy();
            wipe(encodedAck);
            wipe(encodedMap);
        }
    }

    @Test
    public void streamDecoderHandlesSplitsCoalescingAndPoisons() {
        byte[] handshake =
                IdsSocketPairCodec.encodeHandshake(
                        1);
        byte[] keepAlive =
                IdsSocketPairCodec.encodeKeepAlive();
        byte[] ack =
                IdsSocketPairCodec.encodeAck(
                        7,
                        false);
        byte[] combined =
                concatenate(
                        handshake,
                        keepAlive,
                        ack);
        try (IdsSocketPairCodec.StreamDecoder decoder =
                new IdsSocketPairCodec.StreamDecoder()) {
            List<IdsSocketPairCodec.Message> first =
                    decoder.push(
                            Arrays.copyOfRange(
                                    combined,
                                    0,
                                    3));
            assertTrue(first.isEmpty());
            assertEquals(3, decoder.bufferedLength());

            List<IdsSocketPairCodec.Message> rest =
                    decoder.push(
                            Arrays.copyOfRange(
                                    combined,
                                    3,
                                    combined.length));
            try {
                assertEquals(3, rest.size());
                assertEquals(
                        IdsSocketPairCodec.COMMAND_HANDSHAKE,
                        rest.get(0).command);
                assertEquals(
                        IdsSocketPairCodec.COMMAND_KEEP_ALIVE,
                        rest.get(1).command);
                assertEquals(
                        IdsSocketPairCodec.COMMAND_ACK,
                        rest.get(2).command);
                assertEquals(0, decoder.bufferedLength());
            } finally {
                destroyAll(rest);
            }

            assertThrows(
                    IllegalArgumentException.class,
                    () -> decoder.push(
                            hex("01 00 00 00 01 00")));
            assertThrows(
                    IllegalStateException.class,
                    () -> decoder.push(
                            new byte[0]));
        } finally {
            wipe(handshake);
            wipe(keepAlive);
            wipe(ack);
            wipe(combined);
        }
    }

    @Test
    public void fragmentsAt7983AndReassemblesOutOfOrder() {
        byte[] payload =
                new byte[9000];
        for (int index = 0;
                index < payload.length;
                index++) {
            payload[index] =
                    (byte) index;
        }
        IdsSocketPairCodec.DataMessage source =
                new IdsSocketPairCodec.DataMessage(
                        9,
                        3,
                        0,
                        null,
                        MESSAGE_UUID,
                        null,
                        payload,
                        null);
        byte[] original =
                IdsSocketPairCodec.encodeData(
                        source);
        List<byte[]> fragments =
                IdsSocketPairCodec.fragment(
                        0x55667788L,
                        original);
        assertEquals(2, fragments.size());
        assertEquals(
                IdsSocketPairCodec.FRAGMENT_FRAME_LIMIT,
                fragments.get(0).length);
        assertTrue(
                fragments.get(1).length
                        < IdsSocketPairCodec.FRAGMENT_FRAME_LIMIT);

        IdsSocketPairCodec.FragmentMessage first =
                (IdsSocketPairCodec.FragmentMessage)
                        IdsSocketPairCodec.decode(
                                fragments.get(0));
        IdsSocketPairCodec.FragmentMessage second =
                (IdsSocketPairCodec.FragmentMessage)
                        IdsSocketPairCodec.decode(
                                fragments.get(1));
        try (IdsSocketPairCodec.FragmentReassembler reassembler =
                new IdsSocketPairCodec.FragmentReassembler()) {
            assertEquals(
                    IdsSocketPairCodec.FRAGMENT_SLICE_CAPACITY,
                    first.slice.length);
            assertEquals(0, first.fragmentIndex);
            assertEquals(1, second.fragmentIndex);
            assertEquals(2, first.totalFragmentCount);
            assertNull(
                    reassembler.accept(
                            second));
            IdsSocketPairCodec.Message complete =
                    reassembler.accept(
                            first);
            assertNotNull(complete);
            IdsSocketPairCodec.DataMessage decoded =
                    (IdsSocketPairCodec.DataMessage)
                            complete;
            try {
                assertArrayEquals(payload, decoded.payload);
            } finally {
                decoded.destroy();
            }
        } finally {
            first.destroy();
            second.destroy();
            source.destroy();
            wipe(payload);
            wipe(original);
            wipeAll(fragments);
        }
    }

    @Test
    public void duplicateFragmentMustRemainByteIdentical() {
        byte[] payload =
                new byte[9000];
        IdsSocketPairCodec.DataMessage source =
                new IdsSocketPairCodec.DataMessage(
                        1,
                        2,
                        0,
                        null,
                        MESSAGE_UUID,
                        null,
                        payload,
                        null);
        byte[] original =
                IdsSocketPairCodec.encodeData(
                        source);
        List<byte[]> fragments =
                IdsSocketPairCodec.fragment(
                        4,
                        original);
        byte[] changed =
                fragments.get(0).clone();
        changed[changed.length - 1] ^= 1;
        IdsSocketPairCodec.FragmentMessage first =
                (IdsSocketPairCodec.FragmentMessage)
                        IdsSocketPairCodec.decode(
                                fragments.get(0));
        IdsSocketPairCodec.FragmentMessage duplicateChanged =
                (IdsSocketPairCodec.FragmentMessage)
                        IdsSocketPairCodec.decode(
                                changed);
        try (IdsSocketPairCodec.FragmentReassembler reassembler =
                new IdsSocketPairCodec.FragmentReassembler()) {
            assertNull(
                    reassembler.accept(
                            first));
            assertThrows(
                    IllegalArgumentException.class,
                    () -> reassembler.accept(
                            duplicateChanged));
            assertThrows(
                    IllegalStateException.class,
                    () -> reassembler.accept(
                            first));
        } finally {
            first.destroy();
            duplicateChanged.destroy();
            source.destroy();
            wipe(payload);
            wipe(original);
            wipe(changed);
            wipeAll(fragments);
        }
    }

    @Test
    public void rejectsVersionDriftAndMalformedFrames() {
        assertThrows(
                IllegalArgumentException.class,
                () -> IdsSocketPairCodec.decode(
                        hex("02 00 00 00 04 00 00 00 01")));
        assertThrows(
                IllegalArgumentException.class,
                () -> IdsSocketPairCodec.decode(
                        hex("04 00 00 00 03 00 00 00")));
        assertThrows(
                IllegalArgumentException.class,
                () -> IdsSocketPairCodec.decode(
                        hex(
                                "27 00 00 00 0d "
                                        + "01 00 01 01 "
                                        + "02 00 02 00 01 "
                                        + "03 00 01 ff")));
        assertThrows(
                IllegalArgumentException.class,
                () -> new IdsSocketPairCodec.ServiceMapMessage(
                        1,
                        0,
                        "service"));
        assertFalse(
                IdsSocketPairCodec.FRAGMENT_SLICE_CAPACITY
                        >= IdsSocketPairCodec.FRAGMENT_FRAME_LIMIT);
    }

    private static void destroyAll(
            List<IdsSocketPairCodec.Message> messages) {
        for (IdsSocketPairCodec.Message message : messages) {
            message.destroy();
        }
    }

    private static void wipeAll(
            List<byte[]> values) {
        for (byte[] value : values) {
            wipe(value);
        }
    }

    private static byte[] concatenate(
            byte[]... values) {
        ByteArrayOutputStream output =
                new ByteArrayOutputStream();
        for (byte[] value : values) {
            output.writeBytes(
                    value);
        }
        return output.toByteArray();
    }

    @Test
    public void decompressesGzipProtobufPayload() throws Exception {
        byte[] uncompressed = hex("0a 03 01 02 03");
        ByteArrayOutputStream gzipOut = new ByteArrayOutputStream();
        try (java.util.zip.GZIPOutputStream gzip = new java.util.zip.GZIPOutputStream(gzipOut)) {
            gzip.write(uncompressed);
        }
        byte[] compressed = gzipOut.toByteArray();

        IdsSocketPairCodec.ProtobufMessage outgoing =
                new IdsSocketPairCodec.ProtobufMessage(
                        1,
                        2,
                        IdsSocketPairCodec.FLAG_COMPRESSED,
                        null,
                        "10000000-0000-4000-8000-000000000001",
                        null,
                        2,
                        false,
                        compressed,
                        null);
        byte[] frame = IdsSocketPairCodec.encodeProtobuf(outgoing);

        IdsSocketPairCodec.ProtobufMessage decoded =
                (IdsSocketPairCodec.ProtobufMessage) IdsSocketPairCodec.decode(frame);
        try {
            assertArrayEquals(uncompressed, decoded.payload);
            assertEquals(0, decoded.flags & IdsSocketPairCodec.FLAG_COMPRESSED);
        } finally {
            decoded.destroy();
            wipe(frame);
            wipe(compressed);
        }
    }

    @Test
    public void resourceTransferUsesTheDataEnvelopeAndKeepsTheChunk() throws Exception {
        java.nio.file.Path dir = java.nio.file.Files.createTempDirectory("ids-resource");
        PairedSyncResourceStore.setDirectoryForTesting(dir.toFile());
        byte[] payload = new byte[] {'h', 'i'};
        ByteArrayOutputStream body = new ByteArrayOutputStream();
        body.write(new byte[] {0, 0, 0, 0x50, 0, 1, 0});
        body.write(new byte[] {0, 0, 0, 0});
        byte[] uuid = MESSAGE_UUID.getBytes(java.nio.charset.StandardCharsets.US_ASCII);
        body.write(new byte[] {0, 0, 0, (byte) uuid.length});
        body.write(uuid);
        body.write(payload);
        byte[] raw = body.toByteArray();
        ByteArrayOutputStream frame = new ByteArrayOutputStream();
        frame.write(IdsSocketPairCodec.COMMAND_RESOURCE_TRANSFER);
        frame.write(new byte[] {0, 0, 0, (byte) raw.length});
        frame.write(raw);
        IdsSocketPairCodec.DataMessage decoded =
                (IdsSocketPairCodec.DataMessage) IdsSocketPairCodec.decode(frame.toByteArray());
        try {
            assertEquals(IdsSocketPairCodec.COMMAND_RESOURCE_TRANSFER, decoded.command);
            assertEquals(0x50L, decoded.sequence);
            assertArrayEquals(payload, decoded.payload);
            PairedSyncResourceStore.Result stored = PairedSyncResourceStore.append(decoded);
            assertEquals(2, stored.chunkBytes);
            assertEquals(2L, stored.totalBytes);
            PairedSyncResourceStore.Result repeat = PairedSyncResourceStore.append(decoded);
            assertEquals(0, repeat.chunkBytes);
            assertEquals(2L, repeat.totalBytes);
        } finally {
            decoded.destroy();
            PairedSyncResourceStore.setDirectoryForTesting(null);
        }
    }

    @Test
    public void incompleteZlibDoesNotReplacePayloadWithPartialInflation() {
        byte[] original = new byte[4096];
        for (int i = 0; i < original.length; i++) original[i] = (byte) (i * 17 + i / 37);
        java.util.zip.Deflater compressor = new java.util.zip.Deflater();
        compressor.setInput(original);
        compressor.finish();
        byte[] buffer = new byte[8192];
        int count = compressor.deflate(buffer);
        compressor.end();
        // Removing the checksum leaves decoded bytes but no complete stream.
        byte[] truncated = Arrays.copyOf(buffer, count - 4);
        var outgoing = new IdsSocketPairCodec.DataMessage(IdsSocketPairCodec.COMMAND_DATA,
                90, 1, IdsSocketPairCodec.FLAG_COMPRESSED, null, MESSAGE_UUID, null, truncated, null);
        byte[] frame = IdsSocketPairCodec.encodeData(outgoing);
        var decoded = (IdsSocketPairCodec.DataMessage) IdsSocketPairCodec.decode(frame);
        try {
            assertArrayEquals(truncated, decoded.payload);
            assertEquals(IdsSocketPairCodec.FLAG_COMPRESSED,
                    decoded.flags & IdsSocketPairCodec.FLAG_COMPRESSED);
        } finally { outgoing.destroy(); decoded.destroy(); wipe(frame); }
    }

    @Test
    public void resourceCompressionLeavesOffsetOutsideTheGzipStream() throws Exception {
        byte[] input = new byte[4000];
        for (int i = 0; i < input.length; i++) input[i] = (byte) (i * 73 + i / 127);
        ByteArrayOutputStream packed = new ByteArrayOutputStream();
        try (var gzip = new java.util.zip.GZIPOutputStream(packed)) { gzip.write(input); }
        byte[] payload = java.nio.ByteBuffer.allocate(8 + packed.size())
                .putLong(372000).put(packed.toByteArray()).array();
        var outgoing = new IdsSocketPairCodec.DataMessage(IdsSocketPairCodec.COMMAND_RESOURCE_TRANSFER,
                90, 1, IdsSocketPairCodec.FLAG_COMPRESSED, null, MESSAGE_UUID, null, payload, null);
        byte[] frame = IdsSocketPairCodec.encodeData(outgoing);
        var decoded = (IdsSocketPairCodec.DataMessage) IdsSocketPairCodec.decode(frame);
        try {
            assertEquals(4008, decoded.payload.length);
            assertEquals(372000, java.nio.ByteBuffer.wrap(decoded.payload, 0, 8).getLong());
            assertArrayEquals(input, Arrays.copyOfRange(decoded.payload, 8, decoded.payload.length));
            assertEquals(0, decoded.flags & IdsSocketPairCodec.FLAG_COMPRESSED);
        } finally { outgoing.destroy(); decoded.destroy(); wipe(frame); }
        // Without the flag these are the file's own gzip bytes, not envelope compression.
        var raw = new IdsSocketPairCodec.DataMessage(IdsSocketPairCodec.COMMAND_RESOURCE_TRANSFER,
                91, 1, 0, null, MESSAGE_UUID, null, payload, null);
        frame = IdsSocketPairCodec.encodeData(raw);
        decoded = (IdsSocketPairCodec.DataMessage) IdsSocketPairCodec.decode(frame);
        try { assertArrayEquals(payload, decoded.payload); }
        finally { raw.destroy(); decoded.destroy(); wipe(frame); }
    }

    private static byte[] hex(
            String value) {
        String normalized =
                value.replaceAll(
                        "\\s+",
                        "");
        byte[] output =
                new byte[normalized.length() / 2];
        for (int index = 0;
                index < output.length;
                index++) {
            output[index] =
                    (byte) Integer.parseInt(
                            normalized.substring(
                                    index * 2,
                                    index * 2 + 2),
                            16);
        }
        return output;
    }

    private static void wipe(
            byte[] value) {
        if (value != null) {
            Arrays.fill(
                    value,
                    (byte) 0);
        }
    }
}
